services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.ec.crt:/etc/nginx/ssl/nginx.ec.crt
      - ./nginx/nginx.ec.key:/etc/nginx/ssl/nginx.ec.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABSE: authority_server
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -p$$(echo $$MARIADB_ROOT_PASSWORD)| grep 'mysqld is alive' || exit 1",
        ]
      interval: 2s
      retries: 120