services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABSE: authority_server
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      static-network:
        ipv4_address: 172.22.0.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
