services:
  web:
    build: .
    ports:
      - "2808:2808"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABSE: authority_server
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -p123456 | grep 'mysqld is alive' || exit 1",
        ]
      interval: 2s
      retries: 120
